Repository cloudpilot-ai/karpenter-provider-alibabacloud, pull requests merged in 2025-04, with the labels that each got.

#218 support set password and key pair in ecs node class
  charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
  pkg/apis/v1alpha1/ecsnodeclass.go
  pkg/providers/instance/instance.go
Labels: enhancement, LGTM

#220 chore: release chart package
  charts/index.yaml
  charts/karpenter-0.2.0.tgz
Labels: enhancement

#222 fix family lowercase
  pkg/apis/v1alpha1/ecsnodeclass.go
Labels: bug
